{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: safepoint
    app.kubernetes.io/component: operator
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
  selector:
    app.kubernetes.io/name: safepoint
    app.kubernetes.io/component: operator
{{- end }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: safepoint
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: safepoint
      app.kubernetes.io/component: operator
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      path: /metrics
{{- end }}
