# =============================================================================
# Bu dosya ne ise yarar?
#   Helm sablonu: operator ServiceAccount.
# =============================================================================

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: safepoint
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
